# Appearance
appearance:
  mode: system
  color: emerald
  favicon: icon.png  # static í´ë” ë‚´ì˜ íŒŒë¹„ì½˜ íŒŒì¼ ê²½ë¡œ
# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'ì „ë¶ëŒ€í•™êµ'
    description: 'ì „ë¶ëŒ€í•™êµ ê¹€ì„ ê°• í•™ìƒì˜ ê°œì¸ í•™ìˆ  ì›¹ì‚¬ì´íŠ¸ì…ë‹ˆë‹¤.'
    twitter: 'GetResearchDev'
    keywords: ['ì „ë¶ëŒ€', 'ê¹€ì„ ê°•', 'í•™ìƒ', 'í•™ìˆ ', 'ì—°êµ¬', 'ì»´í“¨í„°ê³µí•™ë¶€', 'ì»´í“¨í„°ì¸ê³µì§€ëŠ¥í•™ë¶€', 'JBNU', 'Kim Sun Gang', 'ì „ë¶ëŒ€í•™êµ', 'ì»´í“¨í„°']
  analytics:
    google_analytics: '' # Google Analytics ì¶”ì  IDë¥¼ ì—¬ê¸°ì— ì¶”ê°€í•˜ì„¸ìš”
  verification:
    google: '' # Google Search Console ì¸ì¦ ì½”ë“œë¥¼ ì—¬ê¸°ì— ì¶”ê°€í•˜ì„¸ìš”

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "ğŸ˜ê¹€ì„ ê°•ğŸ˜"
      filename: 'logo.jpg'

# Site footer
footer:
  copyright:
    notice: 'Â© {year} ê¹€ì„ ê°•. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2006ë…„ 1ì›” 2ì¼'
  time_format: 'ì˜¤í›„ 3ì‹œ 04ë¶„'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

contact:
  view: card

event:
  view: card