# Appearance
appearance:
  mode: system
  color: blue
  favicon: icon.png  # static 폴더 내의 파비콘 파일 경로
# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: '전북대학교'
    description: '전북대학교 김선강 학생의 개인 학술 웹사이트입니다. 전북대학교 컴퓨터공학부/인공지능학부 소속 학생으로, 최신 학술 및 연구 내용을 공유합니다.'
    twitter: 'GetResearchDev'
    keywords: ['전북대', '김선강', '학생', '학술', '연구', '컴퓨터공학부', '컴퓨터인공지능학부', 'JBNU', 'Kim Sun Gang', '전북대학교', '컴퓨터', '전북대 김선강']
  analytics:
    google_analytics: 'G-993QWGF39F' # Google Analytics 추적 ID
    naver_analytics: '' # 네이버 애널리틱스 추적 ID (사용할 경우)
  verification:
    google: 'ca5rkt7mCBsSwVSSzzh14zLVmfJkFFYo5-_2bGeHCHQ' # Google Search Console 인증 코드
    naver: '2bb84b9ab5970606e1f79882761c91b39612ed92'

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: ""
      filename: 'projectwallpaper.gif'

# Site footer
footer:
  copyright:
    notice: '© {year} 김선강. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2006년 1월 2일'
  time_format: '오후 3시 04분'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

